
virt-install:
  name:
    AlmaLinux 10:
      osinfo: almalinux10
      arch:
        x86_64:
          disk-url: https://repo.almalinux.org/almalinux/10.1/cloud/x86_64/images/AlmaLinux-10-GenericCloud-10.1-20251125.0.x86_64.qcow2
          inventory: tests/inventory/almalinux-10-x86_64
        aarch64:
          disk-url: https://repo.almalinux.org/almalinux/10.1/cloud/aarch64/images/AlmaLinux-10-GenericCloud-10.1-20251125.0.aarch64.qcow2
          inventory: tests/inventory/almalinux-10-aarch64
          boot: &boot-hd-also-secure-boot
            uefi:
              secure-boot-check: secure-boot=yes
            hd:
              secure-boot-check: secure-boot=yes
            uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=yes:
              secure-boot-check: secure-boot=yes
            uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
              secure-boot-check: secure-boot=no
    Fedora 43 (no cloud-init):
      osinfo: fedora42
      arch:
        x86_64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/x86_64/images/Fedora-Server-Guest-Generic-43-1.6.x86_64.qcow2
          inventory: tests/inventory/fedora-43-server-x86_64
        aarch64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/aarch64/images/Fedora-Server-Guest-Generic-43-1.6.aarch64.qcow2
          inventory: tests/inventory/fedora-43-server-aarch64
          boot: &boot-no-secure-boot
            uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
              secure-boot-check: secure-boot=no
          virt-customize: >
            --ssh-inject root:file:/home/runner/.ssh/id_rsa.pub
            --firstboot-command 'restorecon -rvv /root/.ssh'
            --link /dev/null:/etc/systemd/system/initial-setup.service
            --mkdir /etc/systemd/system.conf.d
            --copy-in tests/systemd-device-timeout.conf:/etc/systemd/system.conf.d
            --no-selinux-relabel
      virt-customize: >
        --ssh-inject root:file:/home/runner/.ssh/id_rsa.pub
        --firstboot-command 'restorecon -rvv /root/.ssh'
        --link /dev/null:/etc/systemd/system/initial-setup.service
        --no-selinux-relabel
    Fedora 43:
      osinfo: fedora42
      arch:
        x86_64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
          inventory: tests/inventory/fedora-43-x86_64
        aarch64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/aarch64/images/Fedora-Cloud-Base-Generic-43-1.6.aarch64.qcow2
          inventory: tests/inventory/fedora-43-aarch64
          boot:
            <<: *boot-no-secure-boot
          virt-customize: &systemd-device-timeout >
            --mkdir /etc/systemd/system.conf.d
            --copy-in tests/systemd-device-timeout.conf:/etc/systemd/system.conf.d
            --no-selinux-relabel
    Fedora 42:
      osinfo:
        fedora42:
        generic:
          boot:
           hd:
             secure-boot-check: secure-boot=missing
           uefi:
             secure-boot-check: secure-boot=no
           uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
             secure-boot-check: secure-boot=no
      arch:
        x86_64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
          inventory: tests/inventory/fedora-42-x86_64
        aarch64:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/aarch64/images/Fedora-Cloud-Base-Generic-42-1.1.aarch64.qcow2
          inventory: tests/inventory/fedora-42-aarch64
          boot:
            <<: *boot-no-secure-boot
          virt-customize: *systemd-device-timeout
    Ubuntu 24.04:
      osinfo: ubuntu24.04
      arch:
        x86_64:
          disk-url: https://cloud-images.ubuntu.com/releases/noble/release-20260321/ubuntu-24.04-server-cloudimg-amd64.img
          inventory: tests/inventory/ubuntu-24.04-amd64
        aarch64:
          disk-url: https://cloud-images.ubuntu.com/releases/noble/release-20260321/ubuntu-24.04-server-cloudimg-arm64.img
          inventory: tests/inventory/ubuntu-24.04-arm64
          boot:
            <<: *boot-hd-also-secure-boot
    Debian 13:
      osinfo: debian13
      arch:
        x86_64:
          disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-amd64-20260316-2418.qcow2
          inventory: tests/inventory/debian-13-amd64
        aarch64:
          disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-arm64-20260316-2418.qcow2
          inventory: tests/inventory/debian-13-arm64
    Arch Linux latest:
      osinfo: archlinux
      arch: x86_64
      disk-url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
      inventory: tests/inventory/arch-linux-latest-x86_64
    Alpine Linux 3.23:
      osinfo: alpinelinux3.21
      arch:
        x86_64:
          disk-url: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/nocloud_alpine-3.23.3-x86_64-uefi-cloudinit-r0.qcow2
          inventory: tests/inventory/alpine-linux-3.23-x86_64
        aarch64:
          disk-url: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/nocloud_alpine-3.23.3-aarch64-uefi-cloudinit-r0.qcow2
          inventory: tests/inventory/alpine-linux-3.23-aarch64
      boot: uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no
      secure-boot-check: secure-boot=no
      virt-customize: >
        --run-command 'sed -i "s/^root:!\\*:/root:*:/" /etc/shadow'

  osinfo: linux2024

  boot:
    uefi:
      secure-boot-check: secure-boot=yes
    hd:
      secure-boot-check: secure-boot=missing
    uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=yes:
      secure-boot-check: secure-boot=yes
    uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
      secure-boot-check: secure-boot=no

  second-machine:
    - recreate
    - local-file
    - multihost

  exclude:
    - disk-url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
      secure-boot-check: secure-boot=yes
    - disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-amd64-20260316-2418.qcow2
      boot: hd
    - disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-arm64-20260316-2418.qcow2
      boot: hd
    - disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/aarch64/images/Fedora-Server-Guest-Generic-43-1.6.aarch64.qcow2

