
virt-install:
  name:
    AlmaLinux 10:
      osinfo: almalinux10
      disk-url: https://repo.almalinux.org/almalinux/10.1/cloud/x86_64/images/AlmaLinux-10-GenericCloud-10.1-20251125.0.x86_64.qcow2
      inventory: tests/inventory/almalinux-10
    Fedora 43 (no cloud-init):
      osinfo: fedora42
      disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Server/x86_64/images/Fedora-Server-Guest-Generic-43-1.6.x86_64.qcow2
      inventory: tests/inventory/fedora-43-server
      virt-customize: >
        --ssh-inject root:file:/home/runner/.ssh/id_rsa.pub
        --firstboot-command 'restorecon -rvv /root/.ssh'
        --link /dev/null:/etc/systemd/system/initial-setup.service
        --no-selinux-relabel
    Fedora 43:
      osinfo: fedora42
      disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
      inventory: tests/inventory/fedora-43
    Fedora 42:
      osinfo:
        fedora42:
        generic:
          boot:
           hd:
             secure-boot-check: secure-boot=missing
           uefi:
             secure-boot-check: secure-boot=no
           uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
             secure-boot-check: secure-boot=no
      disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
      inventory: tests/inventory/fedora-42
    Ubuntu 24.04:
      osinfo: ubuntu24.04
      disk-url: https://cloud-images.ubuntu.com/releases/noble/release-20260321/ubuntu-24.04-server-cloudimg-amd64.img
      inventory: tests/inventory/ubuntu-24.04
    Debian 13:
      osinfo: debian13
      disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-amd64-20260316-2418.qcow2
      inventory: tests/inventory/debian-13
    Arch Linux latest:
      osinfo: archlinux
      disk-url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
      inventory: tests/inventory/arch-linux-latest
    Alpine Linux 3.23:
      osinfo: alpinelinux3.21
      disk-url: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/nocloud_alpine-3.23.3-x86_64-uefi-cloudinit-r0.qcow2
      inventory: tests/inventory/alpine-linux-3.23
      boot: uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no
      secure-boot-check: secure-boot=no
      virt-customize: >
        --run-command 'sed -i "s/^root:!\\*:/root:*:/" /etc/shadow'

  osinfo: linux2024

  boot:
    uefi:
      secure-boot-check: secure-boot=yes
    hd:
      secure-boot-check: secure-boot=missing
    uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=yes:
      secure-boot-check: secure-boot=yes
    uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no:
      secure-boot-check: secure-boot=no

  second-machine:
    - recreate
    - local-file
    - multihost

  exclude:
    - disk-url: https://fastly.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2
      secure-boot-check: secure-boot=yes
    - disk-url: https://cloud.debian.org/images/cloud/trixie/20260316-2418/debian-13-genericcloud-amd64-20260316-2418.qcow2
      boot: hd

