name: Create virtual machine
description: Fetch a VM image and create a virtual machine using virt-install
inputs:
  disk-url:
    description: URL of disk to use
    required: true
  vm-name:
    description: Name of the VM (libvirt domain)
    default: vm1.example.com
  osinfo:
    description: The osinfo parameter to virt-install
    default: detect=on
runs:
  using: composite
  steps:
    - run: |
        echo "Checking the inputs.vm-name value [$INPUT_VM_NAME] is sane."
        [[ "$INPUT_VM_NAME" =~ ^[-a-z0-9_.]+$ ]]
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash
    - run: |
        sudo apt update
        # we install libvirt-daemon-system and not just libvirt-daemon
        # to get the libvirtd.service which configures virbr0
        sudo apt install genisoimage libvirt-daemon-system virtinst expect
      shell: bash
    - run: |
        mkdir -p virt-install-images/base
        FILENAME="${INPUT_DISK_URL##*/}"
        curl -LSs -o virt-install-images/base/"$FILENAME" "$INPUT_DISK_URL"
        qemu-img create -f qcow2 -b base/"$FILENAME" -F qcow2 virt-install-images/'${{ inputs.vm-name }}'.qcow2
      env:
        INPUT_DISK_URL: ${{ inputs.disk-url }}
      shell: bash -euxo pipefail {0}
    - run: ssh-keygen -N '' -f ~/.ssh/id_rsa
      shell: bash
    - run: |
        (
          cd virt-install-images
          echo 'instance-id: ${{ inputs.vm-name }}' | tee meta-data
          (
            echo '#cloud-config'
            echo 'disable_root: false'
            echo 'ssh_authorized_keys:'
            sed 's/^/  - /' ~/.ssh/id_rsa.pub
          ) | tee user-data
          genisoimage -output '${{ inputs.vm-name }}'-cloud-init.iso -volid cidata -joliet -rock user-data meta-data
        )
      shell: bash -euxo pipefail {0}
    - run: |
        systemctl status libvirtd.service
        ip a
        sudo chmod a+rw /dev/kvm
        sudo mkdir /etc/qemu && echo 'allow virbr0' | sudo tee /etc/qemu/bridge.conf
        sudo chmod u+s /usr/lib/qemu/qemu-bridge-helper
      shell: bash -euxo pipefail {0}
    - run: |
        virt-install --connect qemu:///session --graphics none --noautoconsole \
          --name '${{ inputs.vm-name }}' --network bridge=virbr0,model=virtio --memory 2000 --import \
          --disk virt-install-images/'${{ inputs.vm-name }}'.qcow2 \
          --disk path=virt-install-images/'${{ inputs.vm-name }}'-cloud-init.iso,device=cdrom \
          --osinfo "$INPUT_OSINFO" --boot uefi
      env:
        INPUT_OSINFO: ${{ inputs.osinfo }}
      shell: bash
    - run: |
        expect util/virsh-console.expect '${{ inputs.vm-name }}'
        MAC=$( virsh --connect qemu:///session dumpxml '${{ inputs.vm-name }}' | xmllint --xpath 'string(/domain/devices/interface/mac/@address)' - )
        sudo virsh net-dhcp-leases default --mac $MAC
        IP=$( sudo virsh net-dhcp-leases default --mac $MAC | awk 'BEGIN { MAC=ARGV[1] ; delete ARGV[1] } $0 ~ MAC { gsub("/.*$", "", $5); print $5 }' $MAC )
        echo "$IP ${{ inputs.vm-name }}" | sudo tee -a /etc/hosts
      shell: bash -euxo pipefail {0}
    - run: ssh -o 'StrictHostKeyChecking accept-new' -v root@'${{ inputs.vm-name }}' true
      shell: bash
