name: Create virtual machine
description: Fetch a VM image and create a virtual machine using virt-install
inputs:
  disk-url:
    description: URL of disk to use
    required: true
  vm-name:
    description: Name of the VM (libvirt domain)
    default: vm1.example.com
  osinfo:
    description: The osinfo parameter to virt-install
    default: generic
runs:
  using: composite
  steps:
    - run: |
        echo "Checking the inputs.vm-name value [$INPUT_VM_NAME] is sane."
        [[ "$INPUT_VM_NAME" =~ ^[a-z0-9_][-a-z0-9_.]*$ ]]
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash
    - run: |
        sudo apt update
      shell: |
        bash -euo pipefail -c "echo -n '::group::output of: ' ; head -1 {0} ; trap 'echo ::endgroup::' exit ; chmod u+x {0} ; exec {0}"
    - run: |
        sudo apt install genisoimage libvirt-daemon-system virtinst expect
        # we install libvirt-daemon-system and not just libvirt-daemon
        # to get the libvirtd.service which configures virbr0
      shell: |
        bash -euo pipefail -c "echo -n '::group::output of: ' ; head -1 {0} ; trap 'echo ::endgroup::' exit ; chmod u+x {0} ; exec {0}"
    - run: |
        mkdir -p virt-install-images/base
        FILENAME=
        if [[ "$INPUT_DISK_URL" =~ ^file: ]] ; then
          if [[ "$INPUT_DISK_URL" =~ ^file:/// ]] ; then
            FILENAME="${INPUT_DISK_URL#file://}"
          elif [[ "$INPUT_DISK_URL" =~ ^file://localhost/ ]] ; then
            FILENAME="${INPUT_DISK_URL#file://localhost}"
          elif [[ "$INPUT_DISK_URL" =~ ^file:/ ]] && ! [[ "$INPUT_DISK_URL" =~ ^file:// ]] ; then
            FILENAME="${INPUT_DISK_URL#file:}"
          fi
        fi
        if [ -z "$FILENAME" ] ; then
          FILENAME=base/$( echo -n "$INPUT_DISK_URL" | sha256sum | sed 's/ .*//' )"-${INPUT_DISK_URL##*/}"
          [ -f virt-install-images/"$FILENAME" ] || curl -LSs -o virt-install-images/"$FILENAME" "$INPUT_DISK_URL"
        fi
        qemu-img create -f qcow2 -b "$FILENAME" -F qcow2 virt-install-images/"$INPUT_VM_NAME".qcow2
      env:
        INPUT_DISK_URL: ${{ inputs.disk-url }}
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash -euxo pipefail {0}
    - run: |
        [ -f ~/.ssh/id_rsa ] || ssh-keygen -N '' -f ~/.ssh/id_rsa
      shell: bash
    - run: |
        (
          cd virt-install-images
          echo 'instance-id: $INPUT_VM_NAME' | tee meta-data
          (
            echo '#cloud-config'
            echo 'disable_root: false'
            echo 'ssh_authorized_keys:'
            sed 's/^/  - /' ~/.ssh/id_rsa.pub
          ) | tee user-data
          genisoimage -output "$INPUT_VM_NAME"-cloud-init.iso -volid cidata -joliet -rock user-data meta-data
        )
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash -euxo pipefail {0}
    - run: |
        systemctl status libvirtd.service || true
        ip a
        sudo chmod a+rw /dev/kvm
        sudo mkdir /etc/qemu && echo 'allow virbr0' | sudo tee /etc/qemu/bridge.conf
        sudo chmod u+s /usr/lib/qemu/qemu-bridge-helper
        sudo chmod a+rw /var/run/libvirt/libvirt-sock
      shell: bash -euxo pipefail {0}
    - run: |
        virt-install --graphics none --noautoconsole --noreboot \
          --name "$INPUT_VM_NAME" --network bridge=virbr0,model=virtio --memory 2000 --import \
          --disk virt-install-images/"$INPUT_VM_NAME".qcow2 \
          --disk path=virt-install-images/"$INPUT_VM_NAME"-cloud-init.iso,device=cdrom \
          --osinfo "$INPUT_OSINFO" --boot uefi
        echo '::group::domain XML'
        virsh dumpxml "$INPUT_VM_NAME"
        echo '::endgroup::'
        virsh start "$INPUT_VM_NAME"
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
        INPUT_OSINFO: ${{ inputs.osinfo }}
        LIBVIRT_DEFAULT_URI: qemu:///session
      shell: bash
    - run: |
        expect "$GITHUB_ACTION_PATH"/util/virsh-console.expect "$INPUT_VM_NAME"
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: |
        bash -euo pipefail -c "echo ::group::output of: virsh console ${{ inputs.vm-name }} ; trap 'echo ::endgroup::' exit ; chmod u+x {0} ; exec {0}"
    - run: |
        MAC=$( virsh --connect qemu:///session dumpxml "$INPUT_VM_NAME" | xmllint --xpath 'string(/domain/devices/interface/mac/@address)' - )
        virsh --connect qemu:///system net-dhcp-leases default --mac $MAC
        IP=$( virsh --connect qemu:///system net-dhcp-leases default --mac $MAC | awk 'BEGIN { MAC=ARGV[1] ; delete ARGV[1] } $0 ~ MAC { gsub("/.*$", "", $5); print $5 }' $MAC )
        echo "$IP $INPUT_VM_NAME" | sudo tee -a /etc/hosts
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash -euxo pipefail {0}
    - run: ssh -o 'StrictHostKeyChecking accept-new' -v root@"$INPUT_VM_NAME" true
      env:
        INPUT_VM_NAME: ${{ inputs.vm-name }}
      shell: bash
