name: Retrieve possible osinfo values
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '6 3 * * 1'
jobs:
  osinfo-to-md:
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-26.04
          - ubuntu-24.04
    timeout-minutes: 5
    if: github.event_name != 'schedule' || github.repository == 'adelton/virt-install'
    steps:
      - uses: actions/checkout@v6
      - run: sudo apt update
      - run: sudo apt install osinfo-db xsltproc
      - run: . /etc/os-release && echo "UBUNTU_VERSION=$VERSION_ID" >> $GITHUB_ENV
      - run: git checkout origin/osinfo-test -- docs/osinfo-ubuntu-$UBUNTU_VERSION.md
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      - run: git commit -m 'Reset file content to osinfo-test.' docs/osinfo-ubuntu-$UBUNTU_VERSION.md || true
      - run: util/osinfo-to-md.sh > docs/osinfo-ubuntu-$UBUNTU_VERSION.md
      - run: |
          START_HEAD=$( git rev-parse HEAD )

          OSINFO_DB_VERSION=$( dpkg-query -W -f '${Version}\n' osinfo-db )
          DATE=$( date +%F )
          git add docs/osinfo-ubuntu-$UBUNTU_VERSION.md
          COMMIT_MESSAGE="Update osinfo documentation for osinfo-db $OSINFO_DB_VERSION @ Ubuntu $UBUNTU_VERSION on $DATE."
          git commit -m "$COMMIT_MESSAGE" || true
          git show

          git format-patch "$START_HEAD" --stdout > osinfo-ubuntu-$UBUNTU_VERSION.patch
          [ -s osinfo-ubuntu-$UBUNTU_VERSION.patch ] || rm -f osinfo-ubuntu-$UBUNTU_VERSION.patch
      - uses: actions/upload-artifact@v7
        with:
          path: osinfo-ubuntu-*.patch
          archive: false
          retention-days: 1

  create-pr:
    needs: osinfo-to-md
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          pattern: osinfo-ubuntu-*.patch
          path: osinfo-ubuntu-patches
          merge-multiple: true
      - run: |
          ls osinfo-ubuntu-patches/*.patch || exit
          DATE=$( date +%F )
          BRANCH="osinfo-update/$DATE"
          git checkout -b "$BRANCH" origin/osinfo-test
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git am osinfo-ubuntu-patches/*.patch
          git push origin "$BRANCH:$BRANCH"

          echo '{ "head": "'"$BRANCH"'", "base": "osinfo-test", "title": "Update osinfo documentation '"$DATE"'", "body": "Update the osinfo documentation, capture the up-to-date list of short-ids and/or remove distributions that went EOL." }' \
          | tee /dev/stderr \
          | curl --fail-with-body -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '@-' \
            ${{ github.api_url }}/repos/${{ github.repository }}/pulls
        shell: bash -euxo pipefail {0}
