name: Test virt-install workflow dispatch
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '10 3 * * 1'

jobs:
  test-dispatch:
    name: Dispatch
    runs-on: ubuntu-26.04
    permissions:
      actions: write
    timeout-minutes: 1
    if: github.event_name != 'schedule' || github.repository == 'adelton/virt-install'
    steps:
      - run: |
          curl -sS --fail-with-body -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H 'Content-Type: application/json' \
            -d '{
              "ref": "${{ github.ref }}",
              "inputs": {
                "disk-url": "https://repo.almalinux.org/almalinux/10/cloud/x86_64/images/AlmaLinux-10-GenericCloud-latest.x86_64.qcow2",
                "osinfo": "almalinux10",
                "command": "cat /etc/os-release"
              }}' \
            ${{ github.api_url }}/repos/${{ github.repository }}/actions/workflows/virt-install.yaml/dispatches
