name: Test the action defaults
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
  schedule:
    - cron: '12 3 * * 1'

jobs:
  virt-install-defaults:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-26.04
            disk-url: https://cloud-images.ubuntu.com/releases/resolute/release/ubuntu-26.04-server-cloudimg-amd64v3.vmdk
            secure-boot-check: secure-boot=missing
          - runs-on: ubuntu-26.04
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img
            secure-boot-check: secure-boot=yes
          - runs-on: ubuntu-26.04-arm
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
            secure-boot-check: secure-boot=missing
          - runs-on: ubuntu-26.04-arm
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img
            secure-boot-check: secure-boot=yes
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: ${{ matrix.disk-url }}
        id: run-machine
      - run: ssh root@vm1.example.com cat /etc/os-release
      # With Ubuntu and --osinfo generic and --boot unspecified,
      # we get Secure Boot uspecified on x86_64 but enabled on aarch64
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: vm1.example.com
          condition: ${{ matrix.secure-boot-check }}
      - run: |
          [[ "$IP_ADDRESS" =~ ^192\.168\.122\. ]]
        env:
          IP_ADDRESS: ${{ steps.run-machine.outputs.ip-address }}
