name: Create virtual machine
on:
  - push
  - workflow_dispatch
jobs:
  test-plan:
    name: Generate test plan
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      matrix-run: ${{ steps.produce-matrix.outputs.matrix-run }}
      vm-name: ${{ steps.produce-matrix.outputs.vm-name }}
      vm-name-2: ${{ steps.produce-matrix.outputs.vm-name-2 }}
    steps:
      - uses: actions/checkout@v6
      - id: produce-matrix
        run: |
          if [ -n "$INPUT_DISK_URL" ] ; then
              cat <<EOS | yq . -o json -
                virt-install:
                  disk-url:
                    $INPUT_DISK_URL :
                      name: ${INPUT_DISK_URL##*/}
                      osinfo: $INPUT_OSINFO
                      boot: $INPUT_BOOT
                      virt-customize: $INPUT_VIRT_CUSTOMIZE
          EOS
          else
              yq . -o json .github/virt-install-params.yaml
          fi \
              | tee /dev/stderr \
              | jq -cf ./ci/generate-test-matrix.jq \
              | tee .github/virt-install.json \
              | ( echo -n 'matrix-run=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -sr -f ./ci/test-matrix-to-html.jq < .github/virt-install.json >> $GITHUB_STEP_SUMMARY
          if [ -z "$INPUT_VM_NAME" ] ; then
              INPUT_VM_NAME=machine.example.test
          fi
          echo "vm-name=$INPUT_VM_NAME" >> $GITHUB_OUTPUT
          VM_NAME2="${INPUT_VM_NAME/./-2.}"
          if [ "$INPUT_VM_NAME" == "$VM_NAME2" ] ; then
              VM_NAME2="$INPUT_VM_NAME-2"
          fi
          echo "vm-name-2=$VM_NAME2" >> $GITHUB_OUTPUT
        shell: bash -euxo pipefail {0}
        env:
          INPUT_DISK_URL: ${{ inputs.disk-url }}
          INPUT_OSINFO: ${{ inputs.osinfo }}
          INPUT_BOOT: ${{ inputs.boot }}
          INPUT_VM_NAME: ${{ inputs.vm-name }}
          INPUT_VIRT_CUSTOMIZE: ${{ inputs.virt-customize }}
  virt-install:
    runs-on: ubuntu-latest
    needs: [ test-plan ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.test-plan.outputs.matrix-run) }}
    steps:
      - uses: adelton/virt-install@master
        with:
          disk-url: ${{ matrix.disk-url }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
      - uses: actions/checkout@v6
      - uses: ./.github/actions/inventory
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          compare-dir: ${{ matrix.inventory }}
        if: inputs.disk-url == ''
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          condition: ${{ matrix.secure-boot-check }}
      - run: ssh root@'${{ needs.test-plan.outputs.vm-name }}' "$INPUT_COMMAND"
        if: inputs.command != ''
        env:
          INPUT_COMMAND: ${{ inputs.command }}

      - run: |
          virsh destroy '${{ needs.test-plan.outputs.vm-name }}'
          virsh undefine --nvram '${{ needs.test-plan.outputs.vm-name }}'
          rm -f ~/.ssh/known_hosts
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'
      - uses: adelton/virt-install@master
        with:
          disk-url: ${{ matrix.disk-url }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'recreate'
      - id: fetch-image
        run: |
          curl -LO '${{ matrix.disk-url }}'
          echo "local-image-file=${DISK_URL##*/}" | tee -a $GITHUB_OUTPUT
        if: matrix.second-machine == 'local-file'
        env:
          DISK_URL: ${{ matrix.disk-url }}
      - uses: adelton/virt-install@master
        with:
          disk-url: file://${{ github.workspace }}/${{ steps.fetch-image.outputs.local-image-file }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'local-file'
      - uses: ./.github/actions/inventory
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          compare-dir: ${{ matrix.inventory }}
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          condition: ${{ matrix.secure-boot-check }}
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'

      - id: run-machine-2
        uses: adelton/virt-install@master
        with:
          disk-url: ${{ matrix.disk-url }}
          vm-name: ${{ needs.test-plan.outputs.vm-name-2 }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'multihost'
      - run: |
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' 'ssh-keygen -N "" -f ~/.ssh/id_rsa'
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' 'cat ~/.ssh/id_rsa.pub' | ssh root@'${{ needs.test-plan.outputs.vm-name-2 }}' 'umask 077 && cat > ~/.ssh/authorized_keys'
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' "ssh -o 'StrictHostKeyChecking accept-new' root@'${{ steps.run-machine-2.outputs.ip-address }}' ip a"
        shell: bash -euxo pipefail {0}
        if: matrix.second-machine == 'multihost'
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name-2 }}
          condition: ${{ matrix.secure-boot-check }}
        if: matrix.second-machine == 'multihost'

  virt-install-defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: adelton/virt-install@master
        with:
          disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
      - run: ssh root@vm1.example.com cat /etc/os-release
      - uses: actions/checkout@v6
      # With default boot (uefi) and osinfo (generic), we get Secure Boot disabled
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: vm1.example.com
          # no Secure Boot even with the default --boot=uefi
          # because of the --osinfo=generic default
          condition: secure-boot=no,enrolled-keys=no
