name: Create virtual machine
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      disk-url:
        description: URL of disk to use
      arch:
        description: Non-native architecture (virt-install --arch argument value)
        type: choice
        options:
          - (guess)
          - x86_64
          - aarch64
        default: (guess)
      runs-on:
        description: Runner
        type: choice
        options:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        default: ubuntu-24.04
      vm-name:
        description: Name of the VM (libvirt domain)
        default: vm1.example.com
      osinfo:
        description: The virt-install --osinfo argument value
        default: generic
      boot:
        description: The virt-install --boot argument value
        default: uefi
      virt-customize:
        description: Arguments to virt-customize to be run on the image
      command:
        description: Command to run in the VM

jobs:
  test-plan:
    name: Generate test plan
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      matrix-run: ${{ steps.produce-matrix.outputs.matrix-run }}
      vm-name: ${{ steps.produce-matrix.outputs.vm-name }}
      vm-name-2: ${{ steps.produce-matrix.outputs.vm-name-2 }}
    steps:
      - uses: actions/checkout@v6
      - id: produce-matrix
        run: |
          if [ -n "$INPUT_DISK_URL" ] ; then
              cat <<EOS | yq . -o json -
                virt-install:
                  name:
                    ${INPUT_DISK_URL##*/}:
                      disk-url: $INPUT_DISK_URL
                      arch: $INPUT_ARCH
                      runs-on: $INPUT_RUNS_ON
                      osinfo: $INPUT_OSINFO
                      boot: $INPUT_BOOT
                      virt-customize: $INPUT_VIRT_CUSTOMIZE
          EOS
          else
              yq . -o json .github/virt-install-params.yaml
          fi \
              | tee /dev/stderr \
              | jq -cf ./ci/generate-test-matrix.jq \
              | tee .github/virt-install.json \
              | ( echo -n 'matrix-run=' >> $GITHUB_OUTPUT ; tee -a $GITHUB_OUTPUT )
          jq -sr -f ./ci/test-matrix-to-html.jq < .github/virt-install.json >> $GITHUB_STEP_SUMMARY
          if [ -z "$INPUT_VM_NAME" ] ; then
              INPUT_VM_NAME=machine.example.test
          fi
          echo "vm-name=$INPUT_VM_NAME" >> $GITHUB_OUTPUT
          VM_NAME2="${INPUT_VM_NAME/./-2.}"
          if [ "$INPUT_VM_NAME" == "$VM_NAME2" ] ; then
              VM_NAME2="$INPUT_VM_NAME-2"
          fi
          echo "vm-name-2=$VM_NAME2" >> $GITHUB_OUTPUT
        shell: bash -euxo pipefail {0}
        env:
          INPUT_DISK_URL: ${{ inputs.disk-url }}
          INPUT_ARCH: ${{ (matrix.arch == '(guess)' && '') || matrix.arch }}
          INPUT_RUNS_ON: ${{ inputs.runs-on }}
          INPUT_OSINFO: ${{ inputs.osinfo }}
          INPUT_BOOT: ${{ inputs.boot }}
          INPUT_VM_NAME: ${{ inputs.vm-name }}
          INPUT_VIRT_CUSTOMIZE: ${{ inputs.virt-customize }}
  virt-install:
    runs-on: ${{ matrix.runs-on }}
    needs: [ test-plan ]
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.test-plan.outputs.matrix-run) }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: ${{ matrix.disk-url }}
          arch: ${{ (matrix.arch == '(guess)' && '') || matrix.arch }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
      - uses: ./.github/actions/inventory
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          compare-dir: ${{ matrix.inventory }}
        if: inputs.disk-url == ''
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          condition: ${{ matrix.secure-boot-check }}
      - run: ssh root@'${{ needs.test-plan.outputs.vm-name }}' "$INPUT_COMMAND"
        if: inputs.command != ''
        env:
          INPUT_COMMAND: ${{ inputs.command }}

      - run: |
          virsh destroy '${{ needs.test-plan.outputs.vm-name }}'
          virsh undefine --nvram '${{ needs.test-plan.outputs.vm-name }}'
          rm -f ~/.ssh/known_hosts
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'
      - uses: ./
        with:
          disk-url: ${{ matrix.disk-url }}
          arch: ${{ (matrix.arch == '(guess)' && '') || matrix.arch }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'recreate'
      - id: fetch-image
        run: |
          curl -LO '${{ matrix.disk-url }}'
          echo "local-image-file=${DISK_URL##*/}" | tee -a $GITHUB_OUTPUT
        if: matrix.second-machine == 'local-file'
        env:
          DISK_URL: ${{ matrix.disk-url }}
      - uses: ./
        with:
          disk-url: file://${{ github.workspace }}/${{ steps.fetch-image.outputs.local-image-file }}
          arch: ${{ (matrix.arch == '(guess)' && '') || matrix.arch }}
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'local-file'
      - uses: ./.github/actions/inventory
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          compare-dir: ${{ matrix.inventory }}
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name }}
          condition: ${{ matrix.secure-boot-check }}
        if: matrix.second-machine == 'recreate' || matrix.second-machine == 'local-file'

      - id: run-machine-2
        uses: ./
        with:
          disk-url: ${{ matrix.disk-url }}
          arch: ${{ (matrix.arch == '(guess)' && '') || matrix.arch }}
          vm-name: ${{ needs.test-plan.outputs.vm-name-2 }}
          osinfo: ${{ matrix.osinfo }}
          boot: ${{ matrix.boot }}
          virt-customize: ${{ matrix.virt-customize }}
        if: matrix.second-machine == 'multihost'
      - run: |
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' 'ssh-keygen -N "" -f ~/.ssh/id_rsa'
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' 'cat ~/.ssh/id_rsa.pub' | ssh root@'${{ needs.test-plan.outputs.vm-name-2 }}' 'umask 077 && cat > ~/.ssh/authorized_keys'
          ssh root@'${{ needs.test-plan.outputs.vm-name }}' "ssh -o 'StrictHostKeyChecking accept-new' root@'${{ steps.run-machine-2.outputs.ip-address }}' ip a"
        shell: bash -euxo pipefail {0}
        if: matrix.second-machine == 'multihost'
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ needs.test-plan.outputs.vm-name-2 }}
          condition: ${{ matrix.secure-boot-check }}
        if: matrix.second-machine == 'multihost'

  virt-install-defaults:
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-24.04
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.vmdk
            secure-boot-check: secure-boot=no
          - runs-on: ubuntu-24.04
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img
            secure-boot-check: secure-boot=yes
          - runs-on: ubuntu-24.04-arm
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
            secure-boot-check: secure-boot=no
          - runs-on: ubuntu-24.04-arm
            disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-arm64.img
            secure-boot-check: secure-boot=yes
    if: inputs.disk-url == ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: ${{ matrix.disk-url }}
      - run: ssh root@vm1.example.com cat /etc/os-release
      # With default boot (uefi) and osinfo (generic), we get Secure Boot disabled on x86_64
      # but enabled on aarch64
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: vm1.example.com
          condition: ${{ matrix.secure-boot-check }}
