name: Create virtual machine
on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      disk-url:
        description: URL of disk to use
      vm-name:
        description: Name of the VM (libvirt domain)
        default: vm1.example.com
      osinfo:
        description: The osinfo parameter to virt-install
        default: generic
      boot:
        description: The virt-install --boot argument value
        default: uefi
      command:
        description: Command to run in the VM

jobs:
  virt-install-almalinux:
    runs-on: ubuntu-latest
    if: inputs.disk-url == ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: https://repo.almalinux.org/almalinux/10.1/cloud/x86_64/images/AlmaLinux-10-GenericCloud-10.1-20251125.0.x86_64.qcow2
          osinfo: almalinux10
          boot: hd
      - run: ssh root@vm1.example.com cat /etc/os-release
      - run: ssh root@vm1.example.com ip a
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: vm1.example.com
          condition: secure-boot=missing,enrolled-keys=missing
      - run: virsh destroy vm1.example.com ; virsh undefine --nvram vm1.example.com
      - run: rm -f ~/.ssh/known_hosts
      - uses: ./
        with:
          disk-url: https://repo.almalinux.org/almalinux/10.1/cloud/x86_64/images/AlmaLinux-10-GenericCloud-10.1-20251125.0.x86_64.qcow2
          osinfo: almalinux10
      - run: ssh root@vm1.example.com cat /etc/os-release
      - run: ssh root@vm1.example.com ip a
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: vm1.example.com
          condition: secure-boot=yes,enrolled-keys=yes
  virt-install-fedora:
    runs-on: ubuntu-latest
    if: inputs.disk-url == ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2
          vm-name: fedora-42.example.test
          osinfo: fedora42
          boot: uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no
      - run: ssh root@fedora-42.example.test cat /etc/os-release
      - run: ssh root@fedora-42.example.test dnf install -y net-tools
      - run: ssh root@fedora-42.example.test netstat -ln
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: fedora-42.example.test
          condition: secure-boot=no,enrolled-keys=no
      - run: curl -LO https://download.fedoraproject.org/pub/fedora/linux/releases/43/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
      - uses: ./
        with:
          disk-url: file://${{ github.workspace }}/Fedora-Cloud-Base-Generic-43-1.6.x86_64.qcow2
          vm-name: fedora-43.example.test
          osinfo: fedora42
      - run: ssh root@fedora-43.example.test cat /etc/os-release
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: fedora-43.example.test
          condition: secure-boot=yes,enrolled-keys=yes
  virt-install-ubuntu:
    runs-on: ubuntu-latest
    if: inputs.disk-url == ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
          vm-name: ubuntu.example.test
          osinfo: ubuntu24.04
      - run: ssh root@ubuntu.example.test cat /etc/os-release
      - run: virsh dumpxml ubuntu.example.test
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ubuntu.example.test
          condition: secure-boot=yes,enrolled-keys=yes
      - uses: ./
        with:
          disk-url: https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img
          vm-name: ubuntu-2.example.test
          osinfo: ubuntu24.04
        id: run-ubuntu-2
      - run: ssh root@ubuntu-2.example.test cat /etc/os-release
      - run: ssh root@ubuntu.example.test 'ssh-keygen -N "" -f ~/.ssh/id_rsa'
      - run: ssh root@ubuntu.example.test 'cat ~/.ssh/id_rsa.pub' | ssh root@ubuntu-2.example.test 'umask 077 && cat > ~/.ssh/authorized_keys'
      - run: ssh root@ubuntu.example.test "ssh -o 'StrictHostKeyChecking accept-new' root@${{ steps.run-ubuntu-2.outputs.ip-address }} ip a"
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ubuntu-2.example.test
          condition: secure-boot=yes,enrolled-keys=yes
  virt-install-alpine:
    runs-on: ubuntu-latest
    if: inputs.disk-url == ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: https://dl-cdn.alpinelinux.org/alpine/v3.23/releases/cloud/nocloud_alpine-3.23.3-x86_64-uefi-cloudinit-r0.qcow2
          vm-name: alpine.example.test
          osinfo: alpinelinux3.21
          boot: uefi,firmware.feature0.name=secure-boot,firmware.feature0.enabled=no
      - run: ssh root@alpine.example.test cat /etc/os-release
      - run: virsh dumpxml alpine.example.test
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: alpine.example.test
          condition: secure-boot=no,enrolled-keys=no

  virt-install-manual:
    runs-on: ubuntu-latest
    if: inputs.disk-url != ''
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          disk-url: ${{ inputs.disk-url }}
          vm-name: ${{ inputs.vm-name }}
          osinfo: ${{ inputs.osinfo }}
          boot: ${{ inputs.boot }}
      - run: ssh root@'${{ inputs.vm-name }}' "$INPUT_COMMAND"
        if: inputs.command != ''
        env:
          INPUT_COMMAND: ${{ inputs.command }}
      - uses: ./.github/actions/secure-boot-check
        with:
          vm-name: ${{ inputs.vm-name }}
          condition:
